spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://172.31.16.224:3306/onlinestore?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: demouser
    password: demouserpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  profiles:
    active: test
